### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by glazkov98** [nmihalyov/prime-grid#2]
Сделать возможность скрытия колонок на нужных разрешениях. (.col-md-hidden).
Включить в доку все очевидные классы (.row-break-sm и т.д.).
Сделать .row-break для колонок, чтобы не создавать отдельный тег.

**Comment by nmihalyov** [comment]
1. Prime Grid предусматривает классы (hide-*/show-*) для этих целей
2. Документация была дополнена в новом релизе
3. Баг с row-break был исправлен, но он также должен быть отдельным элементом на странице

https://github.com/nmihalyov/prime-grid/releases/tag/1.4.0
